---

groups:
  - name: elasticsearch
    jobs:
      - elasticsearch-intake
      - elasticsearch-os-compatibility

  - name: logstash
    jobs: []

  - name: kibana
    jobs: []

  - name: beats
    jobs: []

  - name: x-pack
    jobs:
      - elasticsearch-os-compatibility
      - x-pack

  - name: release
    jobs: []


resources:
  - name: elasticsearch:2.4
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
      branch: '2.4'

  - name: x-pack:2.4
    type: git
    source:
      uri: https://github.com/elasticdog/gateway
      branch: '2.4'


jobs:
  - name: elasticsearch-intake
    plan:
      - get: elasticsearch
        resource: elasticsearch:2.4
        trigger: true
      - task: maven check
        file: elasticsearch/ci/tasks/build-intake.yml

  - name: elasticsearch-os-compatibility
    plan:
      - get: elasticsearch
        resource: elasticsearch:2.4
        passed: [elasticsearch-intake]
        trigger: true
      - aggregate:
        - task: linux
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: darwin
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: windows
          file: elasticsearch/ci/tasks/build-linux.yml

  - name: x-pack
    plan:
      - aggregate:
        - get: elasticsearch
          resource: elasticsearch:2.4
          trigger: true
          passed: [elasticsearch-os-compatibility]
        - get: x-pack
          resource: x-pack:2.4
          trigger: true
      - task: integration
        file: x-pack-elasticsearch/ci/tasks/build.yml
