---

groups:
  - name: elasticsearch
    jobs:
      - elasticsearch-intake
      - elasticsearch-os-compatibility
      - elasticsearch-periodic

  - name: logstash
    jobs: []

  - name: kibana
    jobs: []

  - name: beats
    jobs: []

  - name: x-pack
    jobs:
      - elasticsearch-os-compatibility
      - x-pack-elasticsearch
      - x-pack-elasticsearch-periodic

  - name: release
    jobs: []


resources:
  - name: elasticsearch
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
      branch: master

  - name: x-pack-elasticsearch
    type: git
    source:
      uri: https://github.com/elasticdog/gateway
      branch: master

  - name: 1h
    type: time
    source:
      interval: 1h


jobs:
  - name: elasticsearch-intake
    plan:
      - get: elasticsearch
        trigger: true
      - task: gradle check
        file: elasticsearch/ci/tasks/build-intake.yml

  - name: elasticsearch-os-compatibility
    plan:
      - get: elasticsearch
        passed: [elasticsearch-intake]
        trigger: true
      - aggregate:
        - task: linux
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: darwin
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: windows
          file: elasticsearch/ci/tasks/build-linux.yml

  - name: elasticsearch-periodic
    plan:
      - get: elasticsearch
        passed: [elasticsearch-intake]
      - get: 1h
        trigger: true
      - task: gradle build
        file: elasticsearch/ci/tasks/build-linux.yml

  - name: x-pack-elasticsearch
    plan:
      - aggregate:
        - get: elasticsearch
          trigger: true
          passed: [elasticsearch-os-compatibility]
        - get: x-pack-elasticsearch
          trigger: true
      - task: integration
        file: x-pack-elasticsearch/ci/tasks/build.yml

  - name: x-pack-elasticsearch-periodic
    plan:
      - aggregate:
        - get: x-pack-elasticsearch
          passed: [x-pack-elasticsearch]
        - get: elasticsearch
          passed: [x-pack-elasticsearch]
        - get: 1h
          trigger: true
      - task: integration
        file: x-pack-elasticsearch/ci/tasks/build.yml
