---

resources:
  - name: elasticsearch:5.x
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
      branch: 5.x

  - name: x-pack-elasticsearch:5.x
    type: git
    source:
      uri: https://github.com/elasticdog/gateway
      branch: 5.x


jobs:
  - name: intake
    plan:
      - get: elasticsearch
        resource: elasticsearch:5.x
        trigger: true
      - task: maven check
        file: elasticsearch/ci/tasks/build-intake.yml

  - name: os-compatibility
    plan:
      - get: elasticsearch
        resource: elasticsearch:5.x
        passed: [intake]
        trigger: true
      - aggregate:
        - task: linux
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: darwin
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: windows
          file: elasticsearch/ci/tasks/build-linux.yml

  - name: x-pack
    plan:
      - aggregate:
        - get: elasticsearch
          resource: elasticsearch:5.x
          trigger: true
          passed: [os-compatibility]
        - get: x-pack-elasticsearch
          resource: x-pack-elasticsearch:5.x
          trigger: true
      - task: integration
        file: x-pack-elasticsearch/ci/tasks/build.yml
