---

resources:
  - name: elasticsearch
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
    branch: master

  - name: x-pack-elasticsearch
    type: git
    source:
      uri: https://github.com/elasticdog/gateway
    branch: master

  - name: 1h
    type: time
    source:
      interval: 1h


jobs:
  - name: intake
    plan:
      - get: elasticsearch
        trigger: true
      - task: gradle check
        file: elasticsearch/ci/tasks/build-intake.yml

  - name: periodic
    plan:
      - get: elasticsearch
        passed: [intake]
      - get: 1h
        trigger: true
      - task: gradle build
        file: elasticsearch/ci/tasks/build-linux.yml

  - name: os-compatibility
    plan:
      - get: elasticsearch
        passed: [intake]
        trigger: true
      - aggregate:
        - task: linux
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: darwin
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: windows
          file: elasticsearch/ci/tasks/build-linux.yml

  - name: x-pack
    plan:
      - aggregate:
        - get: elasticsearch
          trigger: true
          passed: [os-compatibility]
        - get: x-pack-elasticsearch
          trigger: true
      - task: integration
        file: x-pack-elasticsearch/ci/tasks/build.yml

  - name: x-pack-periodic
    plan:
      - aggregate:
        - get: x-pack-elasticsearch
          passed: [x-pack]
        - get: elasticsearch
          passed: [x-pack]
        - get: 1h
          trigger: true
      - task: integration
        file: x-pack-elasticsearch/ci/tasks/build.yml
