---

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr


resources:
  - name: elasticsearch:master
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
    branch: master

  - name: elasticsearch
    type: pull-request
    source:
      repo: elasticdog/flight-school
      access_token: {{pull-requests-access-token}}
      base: master

  - name: x-pack-elasticsearch
    type: pull-request
    source:
      repo: elasticdog/gateway
      access_token: {{pull-requests-access-token}}
      base: master


jobs:
  - name: elasticsearch
    plan:
      - get: elasticsearch
        trigger: true
        version: every
      - put: elasticsearch
        params:
          path: elasticsearch
          status: pending
      - task: gradle build
        file: elasticsearch/ci/tasks/build-linux.yml
        on_success:
          put: elasticsearch
          params:
            path: elasticsearch
            status: success
        on_failure:
          put: elasticsearch
          params:
            path: elasticsearch
            status: failure

  - name: x-pack-elasticsearch
    plan:
      - aggregate:
        - get: elasticsearch
          resource: elasticsearch:master
        - get: x-pack-elasticsearch
          trigger: true
          version: every
      - put: x-pack-elasticsearch
        params:
          path: x-pack-elasticsearch
          status: pending
      - task: unit tests
        file: x-pack-elasticsearch/ci/tasks/build.yml
        on_success:
          put: x-pack-elasticsearch
          params:
            path: x-pack-elasticsearch
            status: success
        on_failure:
          put: x-pack-elasticsearch
          params:
            path: x-pack-elasticsearch
            status: failure
