---

resources:
  - name: elasticsearch
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
    branch: master

  - name: hourly-timer
    type: time
    source:
      interval: 2m


jobs:
  - name: intake-test
    plan:
      - get: elasticsearch
        trigger: true
      - task: gradle check
        file: elasticsearch/ci/tasks/build-intake.yml

  - name: periodic-tests
    plan:
      - get: elasticsearch
        passed: [intake-test]
      - get: hourly-timer
        trigger: true
      - task: gradle build
        file: elasticsearch/ci/tasks/build-linux.yml

  - name: os-compatibility-tests
    plan:
      - get: elasticsearch
        passed: [intake-test]
        trigger: true
      - aggregate:
        - task: linux
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: darwin
          file: elasticsearch/ci/tasks/build-linux.yml
        - task: windows
          file: elasticsearch/ci/tasks/build-linux.yml
