---

resources:
  - name: elasticsearch
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
    branch: master


jobs:
  - name: intake-tests
    plan:
      - get: elasticsearch
        trigger: true
      - task: tests
        file: elasticsearch/ci/build.yml
