---

resources:
  - name: elasticsearch
    type: git
    source:
      uri: https://github.com/elasticdog/flight-school
    branch: master

  - name: hourly-timer
    type: time
    source:
      interval: 2m


jobs:
  - name: intake-test
    plan:
      - get: elasticsearch
        trigger: true
      - task: 'gradle --info compileJava compileTestJava precommit check'
        file: elasticsearch/ci/intake-build.yml

  - name: periodic-tests
    plan:
      - get: elasticsearch
        passed: [intake-test]
      - get: hourly-timer
        trigger: true
      - task: full-tests
        file: elasticsearch/ci/build.yml
